### ISSUE TITLE
dockertarsum - tarsums are in random order with Docker 1.5

### ISSUE THREAD

**Issue by hudgins** [vbatts/docker-utils#7]
Not 100% sure Docker 1.5 is the cause, but I find that in order to produce an identical result from multiple dockertarsum runs, I have to pipe the result through 'sort'.

Thanks for the useful tool!

**Comment by vbatts** [comment]
@hudgins the order of the layers from `docker save` are not always ordered. Are you needing the checksums to be ordered as well?

**Comment by hudgins** [comment]
I'm doing a hash of the full output. Piping it through 'sort' is a perfectly acceptable solution. Go ahead and close this issue. Thanks for the reply!

**Comment by vbatts** [comment]
<3 thanks for the quick response.
